// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsCbXOM1n98hH4YFaCav48ClSrUKgJ7SA',
    appId: '1:1009605838064:ios:0b14ce4d1bf38f64efee35',
    messagingSenderId: '1009605838064',
    projectId: 'instagramclone-500ec',
    storageBucket: 'instagramclone-500ec.firebasestorage.app',
    iosBundleId: 'com.example.instagrmaui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsCbXOM1n98hH4YFaCav48ClSrUKgJ7SA',
    appId: '1:1009605838064:ios:0b14ce4d1bf38f64efee35',
    messagingSenderId: '1009605838064',
    projectId: 'instagramclone-500ec',
    storageBucket: 'instagramclone-500ec.firebasestorage.app',
    iosBundleId: 'com.example.instagrmaui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkV0WRxSItRGhK5PlmWjXClJ1MCbrptFU',
    appId: '1:1009605838064:web:cac1e7ed6a477356efee35',
    messagingSenderId: '1009605838064',
    projectId: 'instagramclone-500ec',
    authDomain: 'instagramclone-500ec.firebaseapp.com',
    storageBucket: 'instagramclone-500ec.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkV0WRxSItRGhK5PlmWjXClJ1MCbrptFU',
    appId: '1:1009605838064:web:cac1e7ed6a477356efee35',
    messagingSenderId: '1009605838064',
    projectId: 'instagramclone-500ec',
    authDomain: 'instagramclone-500ec.firebaseapp.com',
    storageBucket: 'instagramclone-500ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFT7YJ9f7mZ-IO_4LZ1VBKOKjsWyeCRQ',
    appId: '1:1009605838064:android:7b8abf2c6fefc77aefee35',
    messagingSenderId: '1009605838064',
    projectId: 'instagramclone-500ec',
    storageBucket: 'instagramclone-500ec.firebasestorage.app',
  );

}